### ISSUE TITLE
Output of multiple redirections differs from bash/zsh (which differ from each other also)

### ISSUE THREAD

**Issue by Monsieur-Verdoux** [KrolPolski/minishell#103]
<img width="1001" alt="Screen Shot 2024-04-10 at 7 11 10 PM" src="https://github.com/KrolPolski/minishell/assets/140087779/4854d8fd-b43f-468b-9423-60f2e7eca5fd">

**Comment by KrolPolski** [comment]
I think we can close this as out of scope, this is a non-sensical use case.
