### ISSUE TITLE
Leaks with multiple operators + heredoc

### ISSUE THREAD

**Issue by Monsieur-Verdoux** [KrolPolski/minishell#122]
<img width="977" alt="Screen Shot 2024-04-17 at 4 24 53 PM" src="https://github.com/KrolPolski/minishell/assets/140087779/5c4247b5-b2d6-46d6-b5bd-4fe4b68794f9">

**Comment by Monsieur-Verdoux** [comment]
<img width="910" alt="Screen Shot 2024-04-17 at 4 28 23 PM" src="https://github.com/KrolPolski/minishell/assets/140087779/2174ee4b-6a86-4d61-be7d-3621c8bf22e3">
another case

**Comment by KrolPolski** [comment]
this was fixed in a previous patch.
