### ISSUE TITLE
Env variable expansion should stop when encountering non-letter characters

### ISSUE THREAD

**Issue by Monsieur-Verdoux** [KrolPolski/minishell#124]
<img width="843" alt="Screen Shot 2024-04-17 at 4 30 43 PM" src="https://github.com/KrolPolski/minishell/assets/140087779/18feac3c-bd56-40c4-9115-99d59169c8df">

**Comment by KrolPolski** [comment]
env variables are allowed to have numbers in them, they just can't start with a number. so $A123 is valid, but $123 is not.
So the above looks like it treated $sd as an env variable, and just echoed the rest. Seems like working as intended.
