### ISSUE TITLE
Adding Heredoc functionality

### ISSUE THREAD

**Issue by Monsieur-Verdoux** [KrolPolski/minishell#48]
From Noel's presentation:

"Now heredoc seems to be a bit of a funky concept for some to comprehend, I recommend just messing around with it yourself to get the hang of it. When you execute like the line grep i << LIM it will open this little uh “interface” that lets you write lines until you write LIM (the limiting word in this example, but it’s whatever word you put after the arrow, works with the same logic as the redir filenames). The grep will then use whatever lines you wrote as its input. You can implement this by writing the user input either to a temporary file that you have created or to a pipe. Just take into account that a line like this cat << LIM > file | cat << LIM2 has to work (you have to have two different inputs saved at the same time)."

https://ostechnix.com/bash-heredoc-tutorial/

**Comment by KrolPolski** [comment]
This has been completed.
