### ISSUE TITLE
Sometimes segfaulting after exporting and unsetting env variables

### ISSUE THREAD

**Issue by KrolPolski** [KrolPolski/minishell#62]
```
[rboudwin@c1r6p4.hive.fi ~/Documents/repos/minishell]$ ./minishell
i is 29
[rboudwin@AR-Shell /Users/rboudwin/Documents/repos/minishell]$ export a=b
current length of curr_env is 29
new_env[i] should now have a new value: a=b
current length of curr_env is 30
new_env[i] should now have a new value: a=b
EXECUTE HANDLER EXIT CODE IS 1
[rboudwin@AR-Shell /Users/rboudwin/Documents/repos/minishell]$ export b=c
current length of curr_env is 30
new_env[i] should now have a new value: b=c
current length of curr_env is 31
new_env[i] should now have a new value: b=c
EXECUTE HANDLER EXIT CODE IS 1
[rboudwin@AR-Shell /Users/rboudwin/Documents/repos/minishell]$ unset a
current length of curr_env is 31
current length of curr_env is 30
EXECUTE HANDLER EXIT CODE IS 1
[rboudwin@AR-Shell /Users/rboudwin/Documents/repos/minishell]$ unset b
current length of curr_env is 30
current length of curr_env is 30
[rboudwin@AR-Shell /Users/rboudwin/Documents/repos/minishell]$ echo $a
zsh: segmentation fault  ./minishell
```

This doesn't seem to happen if we export and unset only a single variable, but the above commands reliably segfault. Not sure why.

**Comment by KrolPolski** [comment]
Maybe there is an issue with where the env variable expander is pulling its environmental variables from?

**Comment by Monsieur-Verdoux** [comment]
additional notes so far:
- If you set then unset a variable with the same name twice, then on the second echo attempt it segfaults. However it seems to work if you keep setting then unsetting variables with different names, it echos without segfaulting.
- If you try to unset followed by $ it segfaults
- the bash export when ran without arguments shows the list of currently set env variables, but in a different order than env command. Additionally, if you run, for example, "export a" without assigning a value to it, then if you run export without arguments after, you will see that "a" exists in that list, however when you run env it's not visible there. Maybe there are other differences too.
- in bash if you run "export a b c d" if will create a, b, c and d env variables without assigning values to them. So they are again not visible when running env, but are when running export.
- in bash export followed by non-letter characters gives an error. Ours currently accepts anything like "export 1231[]43[\|-="
