### ISSUE TITLE
Echo with multiple dollar signs as argument

### ISSUE THREAD

**Issue by Monsieur-Verdoux** [KrolPolski/minishell#82]
Not sure if we need to replicate this:

<img width="814" alt="Screen Shot 2024-04-02 at 7 20 59 PM" src="https://github.com/KrolPolski/minishell/assets/140087779/d3489229-583d-491d-af95-64b926812904">

**Comment by KrolPolski** [comment]
$$ expands to the process ID of the shell.
```
($$) Expands to the process ID of the shell. In a subshell, it expands to the process ID of the invoking shell, not the subshell.
```
https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html

These are special parameters not specified in the subject, I think they can be ignored.
