### ISSUE TITLE
Export should probably not allow anything but characters

### ISSUE THREAD

**Issue by Monsieur-Verdoux** [KrolPolski/minishell#86]
Screenshot not from bash, but same issue there

<img width="901" alt="Screen Shot 2024-04-04 at 3 00 33 PM" src="https://github.com/KrolPolski/minishell/assets/140087779/98154a34-8575-4043-a7a6-e304ae68b000">

**Comment by KrolPolski** [comment]
From toying with bash it looks like we should insist on an alphabetic character for the first character and allow numbers but not special characters after that.

**Comment by KrolPolski** [comment]
```
[rboudwin@AR-Shell /Users/rboudwin/Documents/repos/minishell]$ export 2=1
export: 2=1: not a a valid identifier
export: 2=1: not a a valid identifier
[rboudwin@AR-Shell /Users/rboudwin/Documents/repos/minishell]$ export a@
export: a@: not a a valid identifier
export: a@: not a a valid identifier
```
We are getting double output right now, because we are printing error messages in both the parent and the child processes.

**Comment by KrolPolski** [comment]
We are now insisting on the first character being a letter and the rest being a letter or number. Resolved the double printing by changing logic to avoid forking in cases where we only have a single built-in command.
